"""add fk candidates election_id

Revision ID: 615ad8797699
Revises: a02c9b0cb9fb
Create Date: 2026-05-18 17:33:20.877147
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '615ad8797699'
down_revision: Union[str, None] = 'a02c9b0cb9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'candidates', 'elections', ['election_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    # ### end Alembic commands ###
