"""initial schema

Revision ID: a02c9b0cb9fb
Revises: 
Create Date: 2026-05-18 17:12:47.400848
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a02c9b0cb9fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('candidate_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('party_code', sa.String(length=20), nullable=True),
    sa.Column('ballot_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_election_id'), 'candidates', ['election_id'], unique=False)
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('election_type', sa.Enum('presidential', 'congressional', 'regional', 'municipal', 'referendum', name='electiontype'), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_election_code'), 'elections', ['election_code'], unique=True)
    op.create_table('geo_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubigeo', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Enum('national', 'department', 'province', 'district', name='geolevel'), nullable=False),
    sa.Column('parent_ubigeo', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # unique index must exist before the self-referential FK can reference it
    op.create_index(op.f('ix_geo_units_ubigeo'), 'geo_units', ['ubigeo'], unique=True)
    op.create_foreign_key('fk_geo_units_parent_ubigeo', 'geo_units', 'geo_units', ['parent_ubigeo'], ['ubigeo'])
    op.create_index(op.f('ix_geo_units_level'), 'geo_units', ['level'], unique=False)
    op.create_index(op.f('ix_geo_units_parent_ubigeo'), 'geo_units', ['parent_ubigeo'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('ubigeo', sa.String(length=6), nullable=False),
    sa.Column('level', sa.Enum('national', 'department', 'province', 'district', name='geolevel'), nullable=False),
    sa.Column('actas_total', sa.Integer(), nullable=True),
    sa.Column('actas_processed', sa.Integer(), nullable=True),
    sa.Column('actas_pct', sa.Float(), nullable=True),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.Column('votes_cast', sa.Integer(), nullable=True),
    sa.Column('valid_votes', sa.Integer(), nullable=True),
    sa.Column('null_votes', sa.Integer(), nullable=True),
    sa.Column('blank_votes', sa.Integer(), nullable=True),
    sa.Column('turnout_pct', sa.Float(), nullable=True),
    sa.Column('null_pct', sa.Float(), nullable=True),
    sa.Column('blank_pct', sa.Float(), nullable=True),
    sa.Column('winning_margin_pct', sa.Float(), nullable=True),
    sa.Column('leading_candidate_code', sa.String(length=20), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['ubigeo'], ['geo_units.ubigeo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_election_id'), 'results', ['election_id'], unique=False)
    op.create_index('ix_results_election_ubigeo', 'results', ['election_id', 'ubigeo'], unique=True)
    op.create_index('ix_results_level', 'results', ['level'], unique=False)
    op.create_index(op.f('ix_results_ubigeo'), 'results', ['ubigeo'], unique=False)
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'partial', name='scraperstatus'), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_upserted', sa.Integer(), nullable=False),
    sa.Column('last_ubigeo_processed', sa.String(length=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_runs_election_id'), 'scraper_runs', ['election_id'], unique=False)
    op.create_table('candidate_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('vote_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_results_candidate_id'), 'candidate_results', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_results_result_candidate', 'candidate_results', ['result_id', 'candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_results_result_id'), 'candidate_results', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_results_result_id'), table_name='candidate_results')
    op.drop_index('ix_candidate_results_result_candidate', table_name='candidate_results')
    op.drop_index(op.f('ix_candidate_results_candidate_id'), table_name='candidate_results')
    op.drop_table('candidate_results')
    op.drop_index(op.f('ix_scraper_runs_election_id'), table_name='scraper_runs')
    op.drop_table('scraper_runs')
    op.drop_index(op.f('ix_results_ubigeo'), table_name='results')
    op.drop_index('ix_results_level', table_name='results')
    op.drop_index('ix_results_election_ubigeo', table_name='results')
    op.drop_index(op.f('ix_results_election_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_geo_units_ubigeo'), table_name='geo_units')
    op.drop_index(op.f('ix_geo_units_parent_ubigeo'), table_name='geo_units')
    op.drop_index(op.f('ix_geo_units_level'), table_name='geo_units')
    op.drop_table('geo_units')
    op.drop_index(op.f('ix_elections_election_code'), table_name='elections')
    op.drop_table('elections')
    op.drop_index(op.f('ix_candidates_election_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
