import type { ResultItem } from "@/lib/types"

export const EG2026_P1_DEPT_RESULTS: ResultItem[] = [
  {
    ubigeo: "010000", geo_name: "Amazonas", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 345245, votes_cast: 215129,
    valid_votes: 163482, null_votes: 51647, blank_votes: 0,
    turnout_pct: 62.31, null_pct: 24.01, blank_pct: 0.0,
    winning_margin_pct: 18.61, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 58275, vote_pct: 35.65 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 32090, vote_pct: 19.63 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 27859, vote_pct: 17.04 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 17186, vote_pct: 10.51 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 9725, vote_pct: 5.95 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 5968, vote_pct: 3.65 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 5947, vote_pct: 3.64 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 4003, vote_pct: 2.45 }
    ],
  },
  {
    ubigeo: "020000", geo_name: "\u00c1ncash", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 971384, votes_cast: 697521,
    valid_votes: 543023, null_votes: 154498, blank_votes: 0,
    turnout_pct: 71.81, null_pct: 22.15, blank_pct: 0.0,
    winning_margin_pct: 3.0, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 134140, vote_pct: 24.7 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 97743, vote_pct: 18.0 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 81477, vote_pct: 15.0 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 54641, vote_pct: 10.06 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 53989, vote_pct: 9.94 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 48017, vote_pct: 8.84 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 40197, vote_pct: 7.4 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 32819, vote_pct: 6.04 }
    ],
  },
  {
    ubigeo: "030000", geo_name: "Apur\u00edmac", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 361765, votes_cast: 255414,
    valid_votes: 200932, null_votes: 54482, blank_votes: 0,
    turnout_pct: 70.6, null_pct: 21.33, blank_pct: 0.0,
    winning_margin_pct: 34.18, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 82531, vote_pct: 41.07 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 37987, vote_pct: 18.91 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 28388, vote_pct: 14.13 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 21643, vote_pct: 10.77 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 13861, vote_pct: 6.9 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 7302, vote_pct: 3.63 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 6349, vote_pct: 3.16 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 2928, vote_pct: 1.46 }
    ],
  },
  {
    ubigeo: "040000", geo_name: "Arequipa", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 1226116, votes_cast: 993917,
    valid_votes: 879399, null_votes: 114518, blank_votes: 0,
    turnout_pct: 81.06, null_pct: 11.52, blank_pct: 0.0,
    winning_margin_pct: 2.76, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 214611, vote_pct: 24.4 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 161532, vote_pct: 18.37 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 94786, vote_pct: 10.78 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 92298, vote_pct: 10.5 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 87829, vote_pct: 9.99 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 80752, vote_pct: 9.18 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 72127, vote_pct: 8.2 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 63548, vote_pct: 7.23 }
    ],
  },
  {
    ubigeo: "050000", geo_name: "Ayacucho", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 524261, votes_cast: 359521,
    valid_votes: 286477, null_votes: 73044, blank_votes: 0,
    turnout_pct: 68.58, null_pct: 20.32, blank_pct: 0.0,
    winning_margin_pct: 23.13, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 89314, vote_pct: 31.18 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 59662, vote_pct: 20.83 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 41070, vote_pct: 14.34 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 41010, vote_pct: 14.32 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 23058, vote_pct: 8.05 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 15722, vote_pct: 5.49 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 7750, vote_pct: 2.71 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 6545, vote_pct: 2.28 }
    ],
  },
  {
    ubigeo: "060000", geo_name: "Cajamarca", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 1172494, votes_cast: 803750,
    valid_votes: 629170, null_votes: 174580, blank_votes: 0,
    turnout_pct: 68.55, null_pct: 21.72, blank_pct: 0.0,
    winning_margin_pct: 28.56, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 268961, vote_pct: 42.75 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 115641, vote_pct: 18.38 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 89279, vote_pct: 14.19 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 70873, vote_pct: 11.26 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 29660, vote_pct: 4.71 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 29048, vote_pct: 4.62 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 20875, vote_pct: 3.32 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 20287, vote_pct: 3.22 }
    ],
  },
  {
    ubigeo: "070000", geo_name: "Callao", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 1136579, votes_cast: 843719,
    valid_votes: 694693, null_votes: 149026, blank_votes: 0,
    turnout_pct: 74.23, null_pct: 17.66, blank_pct: 0.0,
    winning_margin_pct: 16.68, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 166383, vote_pct: 23.95 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 158426, vote_pct: 22.81 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 109331, vote_pct: 15.74 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 102237, vote_pct: 14.72 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 61621, vote_pct: 8.87 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 42553, vote_pct: 6.13 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 32775, vote_pct: 4.72 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 20035, vote_pct: 2.88 }
    ],
  },
  {
    ubigeo: "080000", geo_name: "Cusco", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 339448, votes_cast: 218001,
    valid_votes: 172956, null_votes: 45045, blank_votes: 0,
    turnout_pct: 64.22, null_pct: 20.66, blank_pct: 0.0,
    winning_margin_pct: 36.32, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 75063, vote_pct: 43.4 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 33591, vote_pct: 19.42 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 23433, vote_pct: 13.55 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 15996, vote_pct: 9.25 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 12238, vote_pct: 7.08 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 5605, vote_pct: 3.24 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 4077, vote_pct: 2.36 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 2953, vote_pct: 1.71 }
    ],
  },
  {
    ubigeo: "090000", geo_name: "Huancavelica", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 652205, votes_cast: 438333,
    valid_votes: 340936, null_votes: 97397, blank_votes: 0,
    turnout_pct: 67.21, null_pct: 22.22, blank_pct: 0.0,
    winning_margin_pct: 14.48, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 102366, vote_pct: 30.02 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 63587, vote_pct: 18.65 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 52987, vote_pct: 15.54 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 48360, vote_pct: 14.18 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 20181, vote_pct: 5.92 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 20174, vote_pct: 5.92 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 19103, vote_pct: 5.6 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 15879, vote_pct: 4.66 }
    ],
  },
  {
    ubigeo: "100000", geo_name: "Hu\u00e1nuco", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 715645, votes_cast: 583130,
    valid_votes: 481697, null_votes: 101433, blank_votes: 0,
    turnout_pct: 81.48, null_pct: 17.39, blank_pct: 0.0,
    winning_margin_pct: 12.62, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 114653, vote_pct: 23.8 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 98052, vote_pct: 20.36 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 55939, vote_pct: 11.61 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 51550, vote_pct: 10.7 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 47605, vote_pct: 9.88 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 45300, vote_pct: 9.4 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 37264, vote_pct: 7.74 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 31908, vote_pct: 6.62 }
    ],
  },
  {
    ubigeo: "110000", geo_name: "Ica", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 1063935, votes_cast: 786142,
    valid_votes: 635519, null_votes: 150623, blank_votes: 0,
    turnout_pct: 73.89, null_pct: 19.16, blank_pct: 0.0,
    winning_margin_pct: 4.78, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 162500, vote_pct: 25.57 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 108631, vote_pct: 17.09 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 78227, vote_pct: 12.31 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 70985, vote_pct: 11.17 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 69940, vote_pct: 11.01 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 50716, vote_pct: 7.98 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 48223, vote_pct: 7.59 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 45865, vote_pct: 7.22 }
    ],
  },
  {
    ubigeo: "120000", geo_name: "Jun\u00edn", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 1552691, votes_cast: 1166594,
    valid_votes: 932793, null_votes: 233801, blank_votes: 0,
    turnout_pct: 75.13, null_pct: 20.04, blank_pct: 0.0,
    winning_margin_pct: 10.8, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 308921, vote_pct: 33.12 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 188993, vote_pct: 20.26 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 91566, vote_pct: 9.82 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 88291, vote_pct: 9.47 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 76520, vote_pct: 8.2 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 74254, vote_pct: 7.96 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 66168, vote_pct: 7.09 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 38080, vote_pct: 4.08 }
    ],
  },
  {
    ubigeo: "130000", geo_name: "La Libertad", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 1051351, votes_cast: 817863,
    valid_votes: 666815, null_votes: 151048, blank_votes: 0,
    turnout_pct: 77.79, null_pct: 18.47, blank_pct: 0.0,
    winning_margin_pct: 15.67, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 176103, vote_pct: 26.41 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 151340, vote_pct: 22.7 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 71644, vote_pct: 10.74 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 68907, vote_pct: 10.33 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 61658, vote_pct: 9.25 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 57305, vote_pct: 8.59 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 50063, vote_pct: 7.51 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 29795, vote_pct: 4.47 }
    ],
  },
  {
    ubigeo: "140000", geo_name: "Lambayeque", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 8651041, votes_cast: 6909396,
    valid_votes: 6082297, null_votes: 827099, blank_votes: 0,
    turnout_pct: 79.87, null_pct: 11.97, blank_pct: 0.0,
    winning_margin_pct: 14.65, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 1212827, vote_pct: 19.94 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 1150623, vote_pct: 18.92 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 1090388, vote_pct: 17.93 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 919464, vote_pct: 15.12 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 556050, vote_pct: 9.14 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 543350, vote_pct: 8.93 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 414752, vote_pct: 6.82 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 199580, vote_pct: 3.28 }
    ],
  },
  {
    ubigeo: "150000", geo_name: "Lima", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 775923, votes_cast: 454078,
    valid_votes: 341326, null_votes: 112752, blank_votes: 0,
    turnout_pct: 58.52, null_pct: 24.83, blank_pct: 0.0,
    winning_margin_pct: 18.5, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 106389, vote_pct: 31.17 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 96815, vote_pct: 28.36 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 40444, vote_pct: 11.85 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 33655, vote_pct: 9.86 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 22835, vote_pct: 6.69 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 14691, vote_pct: 4.3 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 14264, vote_pct: 4.18 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 12233, vote_pct: 3.58 }
    ],
  },
  {
    ubigeo: "160000", geo_name: "Loreto", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 147577, votes_cast: 104546,
    valid_votes: 80796, null_votes: 23750, blank_votes: 0,
    turnout_pct: 70.84, null_pct: 22.72, blank_pct: 0.0,
    winning_margin_pct: 9.9, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 20567, vote_pct: 25.46 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 18948, vote_pct: 23.45 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 11789, vote_pct: 14.59 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 10948, vote_pct: 13.55 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 6506, vote_pct: 8.05 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 5087, vote_pct: 6.3 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 4190, vote_pct: 5.19 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 2761, vote_pct: 3.42 }
    ],
  },
  {
    ubigeo: "170000", geo_name: "Madre de Dios", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 164628, votes_cast: 131316,
    valid_votes: 113954, null_votes: 17362, blank_votes: 0,
    turnout_pct: 79.77, null_pct: 13.22, blank_pct: 0.0,
    winning_margin_pct: 6.27, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 41126, vote_pct: 36.09 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 14719, vote_pct: 12.92 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 13899, vote_pct: 12.2 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 11986, vote_pct: 10.52 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 11909, vote_pct: 10.45 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 7569, vote_pct: 6.64 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 6601, vote_pct: 5.79 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 6145, vote_pct: 5.39 }
    ],
  },
  {
    ubigeo: "180000", geo_name: "Moquegua", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 223695, votes_cast: 146044,
    valid_votes: 115752, null_votes: 30292, blank_votes: 0,
    turnout_pct: 65.29, null_pct: 20.74, blank_pct: 0.0,
    winning_margin_pct: 0.2, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 30597, vote_pct: 26.43 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 21842, vote_pct: 18.87 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 21606, vote_pct: 18.67 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 13855, vote_pct: 11.97 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 10281, vote_pct: 8.88 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 7650, vote_pct: 6.61 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 5183, vote_pct: 4.48 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 4738, vote_pct: 4.09 }
    ],
  },
  {
    ubigeo: "190000", geo_name: "Pasco", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 1534085, votes_cast: 1147464,
    valid_votes: 880019, null_votes: 267445, blank_votes: 0,
    turnout_pct: 74.8, null_pct: 23.31, blank_pct: 0.0,
    winning_margin_pct: 16.57, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 246696, vote_pct: 28.03 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 196635, vote_pct: 22.34 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 100908, vote_pct: 11.47 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 93588, vote_pct: 10.63 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 77122, vote_pct: 8.76 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 65325, vote_pct: 7.42 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 58795, vote_pct: 6.68 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 40950, vote_pct: 4.65 }
    ],
  },
  {
    ubigeo: "200000", geo_name: "Piura", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 963489, votes_cast: 769606,
    valid_votes: 650408, null_votes: 119198, blank_votes: 0,
    turnout_pct: 79.88, null_pct: 15.49, blank_pct: 0.0,
    winning_margin_pct: 21.07, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 223466, vote_pct: 34.36 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 162460, vote_pct: 24.98 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 115259, vote_pct: 17.72 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 73801, vote_pct: 11.35 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 26989, vote_pct: 4.15 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 25389, vote_pct: 3.9 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 12442, vote_pct: 1.91 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 10602, vote_pct: 1.63 }
    ],
  },
  {
    ubigeo: "210000", geo_name: "Puno", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 723605, votes_cast: 533409,
    valid_votes: 389735, null_votes: 143674, blank_votes: 0,
    turnout_pct: 73.72, null_pct: 26.94, blank_pct: 0.0,
    winning_margin_pct: 0.68, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 93288, vote_pct: 23.94 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 90655, vote_pct: 23.26 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 84304, vote_pct: 21.63 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 44306, vote_pct: 11.37 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 22894, vote_pct: 5.87 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 19793, vote_pct: 5.08 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 17394, vote_pct: 4.46 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 17101, vote_pct: 4.39 }
    ],
  },
  {
    ubigeo: "220000", geo_name: "San Mart\u00edn", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 302616, votes_cast: 248969,
    valid_votes: 220730, null_votes: 28239, blank_votes: 0,
    turnout_pct: 82.27, null_pct: 11.34, blank_pct: 0.0,
    winning_margin_pct: 5.06, leading_candidate_code: "F2",
    candidates: [
      { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 69926, vote_pct: 31.68 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 32316, vote_pct: 14.64 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 26302, vote_pct: 11.92 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 25263, vote_pct: 11.45 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 21938, vote_pct: 9.94 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 16162, vote_pct: 7.32 },
          { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 15125, vote_pct: 6.85 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 13698, vote_pct: 6.21 }
    ],
  },
  {
    ubigeo: "230000", geo_name: "Tacna", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 181317, votes_cast: 141754,
    valid_votes: 110792, null_votes: 30962, blank_votes: 0,
    turnout_pct: 78.18, null_pct: 21.84, blank_pct: 0.0,
    winning_margin_pct: 27.17, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 37850, vote_pct: 34.16 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 25245, vote_pct: 22.79 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 16426, vote_pct: 14.83 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 7748, vote_pct: 6.99 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 6556, vote_pct: 5.92 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 6072, vote_pct: 5.48 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 5455, vote_pct: 4.92 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 5440, vote_pct: 4.91 }
    ],
  },
  {
    ubigeo: "240000", geo_name: "Tumbes", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 858967, votes_cast: 671545,
    valid_votes: 577304, null_votes: 94241, blank_votes: 0,
    turnout_pct: 78.18, null_pct: 14.03, blank_pct: 0.0,
    winning_margin_pct: 17.69, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 119476, vote_pct: 20.7 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 115652, vote_pct: 20.03 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 86785, vote_pct: 15.03 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 86599, vote_pct: 15.0 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 69984, vote_pct: 12.12 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 47105, vote_pct: 8.16 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 34326, vote_pct: 5.95 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 17377, vote_pct: 3.01 }
    ],
  },
  {
    ubigeo: "250000", geo_name: "Ucayali", level: "department",
    actas_total: null, actas_processed: null, actas_pct: null, scraped_at: null,
    registered_voters: 453928, votes_cast: 302464,
    valid_votes: 225500, null_votes: 76964, blank_votes: 0,
    turnout_pct: 66.63, null_pct: 25.45, blank_pct: 0.0,
    winning_margin_pct: 16.83, leading_candidate_code: "F1",
    candidates: [
      { candidate_code: "F1", full_name: "Keiko Fujimori Higuchi", party_name: "Fuerza Popular", votes: 66994, vote_pct: 29.71 },
          { candidate_code: "O6", full_name: "Otros candidatos", party_name: "Varios", votes: 55109, vote_pct: 24.44 },
          { candidate_code: "F2", full_name: "Andr\u00e9s S\u00e1nchez Palomino", party_name: "Juntos x Per\u00fa", votes: 29038, vote_pct: 12.88 },
          { candidate_code: "O2", full_name: "Nicanor Boluarte \u00c1lvarez", party_name: "Alianza por el Progreso", votes: 23429, vote_pct: 10.39 },
          { candidate_code: "O4", full_name: "Ricardo Belmont Cassinelli", party_name: "Partido C\u00edvico Obras", votes: 19083, vote_pct: 8.46 },
          { candidate_code: "O1", full_name: "Rafael L\u00f3pez Aliaga Cazorla", party_name: "Renovaci\u00f3n Popular", votes: 12894, vote_pct: 5.72 },
          { candidate_code: "O3", full_name: "Fernando Nieto Gamboa", party_name: "Avancemos", votes: 9938, vote_pct: 4.41 },
          { candidate_code: "O5", full_name: "Sandro L\u00f3pez Chau", party_name: "Ahora Naci\u00f3n - AN", votes: 9015, vote_pct: 4.0 }
    ],
  },
]
